version: 2

jobs:
  # Basic testing of a new commit to any branch.
  test:
    docker:
      - image: birdofpreyru/mythril:0.0.1

    steps:
      - checkout:
          path: /home/mythril

      - run:
          name: Installing mythril tools
          command: cd /home && ./install-mythril-tools.sh laser-ethereum

      - run:
          background: true
          name: Launch of background geth instance
          command: geth --syncmode full --rpc --shh

      - run:
          name: Unit-testing
          command: cd /home/mythril && ./all_tests.sh

workflows:
  version: 2
  build:
    jobs:
      - test
